# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-01-08 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('mobileNumber', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='members',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Team'),
        ),
        migrations.AddField(
            model_name='members',
            name='teamLeader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TechProfile'),
        ),
    ]
